# syntax=docker/dockerfile:1
FROM alpine:3.14

ARG HOSTNAME
ARG SRT_SUBSCRIBE_PORT

RUN mkdir -p /etc/lighttpd
WORKDIR /etc/lighttpd
COPY ./lighttpd.conf .
COPY ./www /www

RUN sed -i "s/\(var web_url = \).*/\1\"\/backend\";/g" /www/js/config.js
RUN sed -i "s/\(var srt_url = \"srt:\/\/\).*/\1$HOSTNAME:$SRT_SUBSCRIBE_PORT\";/g" /www/js/config.js

RUN apk add lighttpd

CMD ["lighttpd", "-D", "-f", "lighttpd.conf"]
