# syntax=docker/dockerfile:1
FROM alpine:3.14

ARG HOSTNAME
ARG SRT_SUBSCRIBE_PORT

COPY ./www /www

RUN sed -i "s/\(var web_url = \).*/\1\"\/backend\";/g" /www/js/config.js &&\
sed -i "s/\(var srt_url = \"srt:\/\/\).*/\1$HOSTNAME:$SRT_SUBSCRIBE_PORT\";/g" /www/js/config.js &&\
apk --no-cache add lighttpd &&\
mkdir -p /etc/lighttpd

WORKDIR /etc/lighttpd

COPY ./lighttpd.conf .


CMD ["lighttpd", "-D", "-f", "lighttpd.conf"]